version: "3.8"

services:
  enoca-challenge:
    image: emirhanusta/enoca-challenge:latest
    container_name: enoca-challenge
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:ecommerceDB
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    networks:
      - enoca-network

networks:
  enoca-network:
    driver: bridge
